set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property PACKAGE_PIN G22 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -name sys_clk -period 20 [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {qspi_flash_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io3_io]
set_property PACKAGE_PIN C23 [get_ports {qspi_flash_ss_io[0]}]
set_property PACKAGE_PIN B24 [get_ports qspi_flash_io0_io]
set_property PACKAGE_PIN A25 [get_ports qspi_flash_io1_io]
set_property PACKAGE_PIN B22 [get_ports qspi_flash_io2_io]
set_property PACKAGE_PIN A22 [get_ports qspi_flash_io3_io]


set_property PACKAGE_PIN B17 [get_ports uart_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_0_rxd]
set_property PACKAGE_PIN A17 [get_ports uart_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_0_txd]


set_property PACKAGE_PIN G26 [get_ports {gpio_tri_io[7]}]
set_property PACKAGE_PIN E26 [get_ports {gpio_tri_io[6]}]
set_property PACKAGE_PIN G25 [get_ports {gpio_tri_io[5]}]
set_property PACKAGE_PIN D26 [get_ports {gpio_tri_io[4]}]

set_property PACKAGE_PIN D25 [get_ports {gpio_tri_io[3]}]
set_property PACKAGE_PIN C26 [get_ports {gpio_tri_io[2]}]
set_property PACKAGE_PIN D23 [get_ports {gpio_tri_io[1]}]
set_property PACKAGE_PIN A23 [get_ports {gpio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[*]}]

create_clock -period 8.000 -name rgmii_rxc [get_ports rgmii_rxc]
#create_clock -period 8.000 -name rgmii_txc [get_ports rgmii_txc]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H22 } [get_ports {phy_reset_out[0]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA25} [get_ports {mdio_mdc}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y25 } [get_ports {mdio_mdio_io}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V26 } [get_ports {rgmii_rd[0]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V21 } [get_ports {rgmii_rd[1]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U24 } [get_ports {rgmii_rd[2]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U25 } [get_ports {rgmii_rd[3]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U26 } [get_ports {rgmii_rx_ctl}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA23} [get_ports {rgmii_rxc}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V22  SLEW FAST } [get_ports {rgmii_td[0]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W26  SLEW FAST } [get_ports {rgmii_td[1]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W25  SLEW FAST } [get_ports {rgmii_td[2]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W21  SLEW FAST } [get_ports {rgmii_td[3]}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W23  SLEW FAST } [get_ports {rgmii_tx_ctl}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB24 SLEW FAST } [get_ports {rgmii_txc}]

set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN W1  } [get_ports {phy_reset_out[0]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN Y2  } [get_ports {mdio_mdc}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN Y1  } [get_ports {mdio_mdio_io}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AE2 } [get_ports {rgmii_rd[0]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AE1 } [get_ports {rgmii_rd[1]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AC1 } [get_ports {rgmii_rd[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB1 } [get_ports {rgmii_rd[3]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AF3 } [get_ports {rgmii_rx_ctl}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB2 } [get_ports {rgmii_rxc}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB4 SLEW FAST } [get_ports {rgmii_td[0]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AA4 SLEW FAST } [get_ports {rgmii_td[1]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AA3 SLEW FAST } [get_ports {rgmii_td[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AA2 SLEW FAST } [get_ports {rgmii_td[3]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN Y3  SLEW FAST } [get_ports {rgmii_tx_ctl}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AC2 SLEW FAST } [get_ports {rgmii_txc}]

#set_output_delay 1.2 -max -clock [get_clocks rgmii_txc] [get_ports {rgmii_td[*] rgmii_tx_ctl}]
#set_output_delay -1.2 -min -clock [get_clocks rgmii_txc] [get_ports {rgmii_td[*] rgmii_tx_ctl}]
#set_output_delay 1.2 -max -clock [get_clocks rgmii_txc] [get_ports {rgmii_td[*] rgmii_tx_ctl}] -clock_fall -add_delay 
#set_output_delay -1.2 -min -clock [get_clocks rgmii_txc] [get_ports {rgmii_td[*] rgmii_tx_ctl}] -clock_fall -add_delay

#set_input_delay -clock [get_clocks rgmii_rxc] -max -1 [get_ports {rgmii_rd[*] rgmii_rx_ctl}]
#set_input_delay -clock [get_clocks rgmii_rxc] -min -3 [get_ports {rgmii_rd[*] rgmii_rx_ctl}]
#set_input_delay -clock [get_clocks rgmii_rxc] -clock_fall -max -1 -add_delay [get_ports {rgmii_rd[*] rgmii_rx_ctl}]
#set_input_delay -clock [get_clocks rgmii_rxc] -clock_fall -min -3 -add_delay [get_ports {rgmii_rd[*] rgmii_rx_ctl}]



